### ISSUE TITLE
Program Raises MajsoulDownloadError

### ISSUE THREAD

**Issue by Shar-pei-bear** [ssttkkl/tensoul-py#2]
The program raises MajsoulDownloadError during execution:
```
Traceback (most recent call last):
  File "C:/Users/11416/OneDrive/Desktop/Mahjong/tensoul-py-master/example.py", line 20, in <module>
    logs = asyncio.run(download(username, password, record))
  File "C:\Users\11416\anaconda3\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "C:\Users\11416\anaconda3\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:/Users/11416/OneDrive/Desktop/Mahjong/tensoul-py-master/example.py", line 12, in download
    return await downloader.download(record_uuid)
  File "C:\Users\11416\OneDrive\Desktop\Mahjong\tensoul-py-master\tensoul\downloader.py", line 101, in download
    raise MajsoulDownloadError(code=res.error.code)
tensoul.downloader.MajsoulDownloadError
```
The error code is 1203. The login seems to be successful as I am logged out on the webpage.

Thanks!

**Comment by Shar-pei-bear** [comment]
Never mind, I put in the wrong record ID. But it seems like the generated game log cannot be directly pasted into NAGA.

**Comment by ssttkkl** [comment]
NAGA only accepts single kyoku game log, you may need to do converting by yourself.

A reference can be found here: https://github.com/bot-ssttkkl/nonebot-plugin-nagabus/blob/a027ebbc5600f7efc42d94858a66e1e5c6637b02/nonebot_plugin_nagabus/naga/service.py#L237

**Comment by ssttkkl** [comment]
麻了，中国人跟中国人在讲英文.jpg
